import type { ClosedJob } from "./closed-jobs-types";

/** Sample closed jobs for demo ledger — July 2026 example from product spec */
export const MOCK_CLOSED_JOBS: ClosedJob[] = [
  {
    id: "mock-job-1",
    customerName: "Larry Buckley",
    propertyAddress: "4125 Canyon Oaks Drive, Chico",
    saleAmount: 420,
    saleType: "one_time",
    recurringFrequency: null,
    serviceCategory: "Window Cleaning",
    closedDate: "2026-07-02",
    notes: "Quarterly exterior detail",
    createdAt: "2026-07-02T18:00:00Z",
    createdBy: "Noah Thomas",
    status: "closed",
    source: "mock",
  },
  {
    id: "mock-job-2",
    customerName: "Sarah Mitchell",
    propertyAddress: "892 Magnolia Lane, Chico",
    saleAmount: 285,
    saleType: "recurring_membership",
    recurringFrequency: "monthly",
    serviceCategory: "Full Home Care Plan",
    closedDate: "2026-07-01",
    notes: "Preferred membership signed",
    createdAt: "2026-07-01T16:30:00Z",
    createdBy: "Dasan Gramps",
    status: "closed",
    source: "mock",
  },
  {
    id: "mock-job-3",
    customerName: "James Ruiz",
    propertyAddress: "2201 Bidwell Ave, Chico",
    saleAmount: 650,
    saleType: "one_time",
    recurringFrequency: null,
    serviceCategory: "Pressure Washing",
    closedDate: "2026-07-01",
    notes: "Driveway + patio",
    createdAt: "2026-07-01T11:00:00Z",
    createdBy: "Noah Thomas",
    status: "closed",
    source: "mock",
  },
  {
    id: "mock-job-4",
    customerName: "Whitney Cole",
    propertyAddress: "455 Vallombrosa Ave, Chico",
    saleAmount: 890,
    saleType: "recurring_membership",
    recurringFrequency: "quarterly",
    serviceCategory: "Full Home Care Plan",
    closedDate: "2026-06-28",
    notes: "Estate care tier",
    createdAt: "2026-06-28T20:15:00Z",
    createdBy: "Dasan Gramps",
    status: "closed",
    source: "mock",
  },
  {
    id: "mock-job-5",
    customerName: "Marcus Chen",
    propertyAddress: "1184 Esplanade, Chico",
    saleAmount: 195,
    saleType: "one_time",
    recurringFrequency: null,
    serviceCategory: "Gutter Cleaning",
    closedDate: "2026-06-26",
    notes: "",
    createdAt: "2026-06-26T14:00:00Z",
    createdBy: "Noah Thomas",
    status: "closed",
    source: "mock",
  },
  {
    id: "mock-job-6",
    customerName: "Elena Park",
    propertyAddress: "330 West East Ave, Chico",
    saleAmount: 310,
    saleType: "recurring_membership",
    recurringFrequency: "monthly",
    serviceCategory: "Window Cleaning",
    closedDate: "2026-06-24",
    notes: "Monthly exterior membership",
    createdAt: "2026-06-24T17:45:00Z",
    createdBy: "Dasan Gramps",
    status: "closed",
    source: "mock",
  },
  {
    id: "mock-job-7",
    customerName: "Robert & Linda Hayes",
    propertyAddress: "789 Manzanita Ave, Chico",
    saleAmount: 1200,
    saleType: "recurring_membership",
    recurringFrequency: "annual",
    serviceCategory: "Full Home Care Plan",
    closedDate: "2026-06-20",
    notes: "Annual prepay",
    createdAt: "2026-06-20T10:00:00Z",
    createdBy: "Noah Thomas",
    status: "closed",
    source: "mock",
  },
  {
    id: "mock-job-8",
    customerName: "Angela Brooks",
    propertyAddress: "1560 The Esplanade, Chico",
    saleAmount: 275,
    saleType: "one_time",
    recurringFrequency: null,
    serviceCategory: "Solar Panel Cleaning",
    closedDate: "2026-06-18",
    notes: "",
    createdAt: "2026-06-18T13:20:00Z",
    createdBy: "Dasan Gramps",
    status: "closed",
    source: "mock",
  },
];
